###read all users
GET http://localhost:4000/user-api/users

###create user

POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"himaja",
    "password":"himaja",
    "age":20
}

###user authentication(login)req
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "username":"himaja",
    "password":"himaja"
}


###read user by objid
GET http://localhost:4000/user-api/users/697dbe105c701a18a7e92cda

###update user by objid
PUT http://localhost:4000/user-api/users/697dbe105c701a18a7e92cda
Content-Type: application/json

{
    "username":"himaja",
    "password":"himaja",
    "age":19
}

###delete user by objid
DELETE http://localhost:4000/user-api/users/697dbe105c701a18a7e92cda

###this is request for testing verifyToken middleware
GET http://localhost:4000/user-api/test


///--------------------------------------------------------------------
###get all the products
GET http://localhost:4000/products-api/products

###create a product
POST http://localhost:4000/products-api/products
Content-Type: application/json

{
    "productname":"Laptop",
    "modelname":"HP",
    "price":61000
}

###